language: d

d:
 - dmd-2.072.2
 - ldc-1.1.0-beta6
 - ldc-1.0.0

matrix:
  allow_failures:
    - d: ldc-1.1.0-beta6
    - d: ldc-1.0.0 # remove when ldc crash is fixed

before_install:
# Add repo for 16.04. Fresh libraries needed
  - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu xenial main universe'
  - sudo apt-get -qq update
  - sudo apt-get install -y liblmdb-dev liblz4-dev libenet-dev libglfw3-dev

script:
  - dub test voxelman:engine
  - dub test voxelman:plugins