language: d

d:
 - dmd-2.071.2
 - ldc-1.0.0

matrix:
  allow_failures:
    - d: ldc-1.0.0 # remove when ldc crash is fixed

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblmdb-dev liblz4-dev libglfw3 libenet-dev