language: d

before_install:
  - sudo wget -P /home/travis/ http://mirrors.kernel.org/ubuntu/pool/main/s/sqlite3/libsqlite3-0_3.10.2-1_amd64.deb
  - sudo dpkg -i /home/travis/libsqlite3-0_3.10.0-2_amd64.deb