language: d

d:
 - dmd-2.071.0
 - ldc-1.0.0

matrix:
  allow_failures:
    - ldc-1.0.0 # remove when ldc crash is fixed

before_install:
  - sudo wget -P /home/travis/ http://mirrors.kernel.org/ubuntu/pool/main/s/sqlite3/libsqlite3-0_3.11.0-1ubuntu1_amd64.deb
  - sudo dpkg -i /home/travis/libsqlite3-0_3.11.0-1ubuntu1_amd64.deb