language: d

d:
 - dmd-2.080.0
 - dmd-2.079.1
 - dmd-2.078.3
 - dmd-2.077.1
 - dmd-2.076.1
 - dmd-2.075.1
 - dmd-2.074.1
 - dmd-2.073.2
 - dmd-2.072.2
 - ldc-1.9.0
 - ldc-1.8.0
 - ldc-1.7.0
 - ldc-1.6.0
 - ldc-1.5.0
 - ldc-1.4.0

matrix:
  allow_failures:
    - d:
      - dmd-2.075.1
      - dmd-2.074.1
      - dmd-2.073.2
      - dmd-2.072.2
      - ldc-1.4.0

before_install:
# Add repo for 16.04. Fresh libraries needed
  - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu xenial main universe'
  - sudo apt-get -qq update
  - sudo apt-get install -y liblmdb-dev liblz4-dev libenet-dev libglfw3-dev

script:
  - dub test voxelman:engine
  - dub test voxelman:plugins